#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Denis Peskoff

# Short bio or description (displayed in the header)
description: NLP Researcher

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:  https://avatars0.githubusercontent.com/u/7445414?s=400&v=4
#
# Flags below are optional
#

email: peskoff.d at gmail.com
github: https://github.com/DenisPeskoff
linkedin: https://www.linkedin.com/in/denis-peskoff/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: "assets/media/break.jpg"
      layout: "default"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-JMLV4NMDBJ

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://denis.ai

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ''

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
